### ISSUE TITLE
AUR package and License

### ISSUE THREAD

**Issue by starmatt** [nunofarruca/WindowIsReady_Remover#17]
Hi !

I just wanted to let you know I created an [AUR package](https://aur.archlinux.org/packages/gnome-shell-extension-windowisready_remover/) for your extension.
Also have you considered using a license file ?

Thanks a lot for it, should be default behaviour tbh.

**Comment by myl7** [comment]
https://github.com/nunofarruca/WindowIsReady_Remover/blob/b50f823674f09bb7db970c2b4d93e58157e7eda7/windowIsReady_Remover%40nunofarruca%40gmail.com/metadata.json#L5

Seems the license is available here
