### ISSUE TITLE
GNOME 42 support

### ISSUE THREAD

**Issue by Mershl** [nunofarruca/WindowIsReady_Remover#20]

**Comment by Neon-kernel** [comment]
It would be fantastic, your extension is so useful! Thank you for your awesome work @nunofarruca!

**Comment by nunofarruca** [comment]
Thanks for the heads up to update it.
It's already updated and available on the gnome extensions page.

Cheers

**Comment by Mershl** [comment]
Just updated on Gnome 42.0, rebooted, checked that extension is enabled and Signal (flatpak) popped up a "Signal is ready" notification.

Haven't checked other applications yet.

![image](https://user-images.githubusercontent.com/520251/163726123-20fd900e-b5a9-4d09-84e8-e6f7ecfc5ccb.png)

![image](https://user-images.githubusercontent.com/520251/163726161-86c1d945-467b-425a-8153-5eb7018d2445.png)

**Comment by Mershl** [comment]
Same goes for Firefox. It's safe to say that the extension is not fully working on Gnome 42.0 (tested on Fedora 36 and Wayland).

![image](https://user-images.githubusercontent.com/520251/163865207-98a28b6c-6883-4c0c-a903-5922346642f4.png)

**Comment by nunofarruca** [comment]
Hummm so something changed.
I'll try to have a peek to the code to see if I spot the issue

**Comment by XMoon** [comment]
may this commit change the behavior

https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/26235bbe5433c48b81bd3917aaf9ef14ff1929b2?page=3

**Comment by nunofarruca** [comment]
@XMoon you were totally right, this change breaks the extension.

Today did some major work to clean it up and it's now available to be updated. 
(using new way to disable the event and removing the settings option since was told a new way to detect the issue on old gnome)

I was testing using VM with fedora 36.

**Comment by ZimbiX** [comment]
I can confirm the update is working for me on Gnome 42. Thanks for fixing it =)
