### ISSUE TITLE
GNOME 43 support

### ISSUE THREAD

**Issue by julianfairfax** [nunofarruca/WindowIsReady_Remover#26]
A version with GNOME 43 support would be nice

**Comment by nunofarruca** [comment]
@julianfairfax Hi, thanks for warning me about this. I'll do an update this week as soon as I can.

Will update you then.

**Comment by nunofarruca** [comment]
I added the Gnome 43 support to the extension, can you please check if all is ok, else please tell me if there is any problem.

thanks and sorry for the wait!
