### ISSUE TITLE
Getting an error after Gnome 43 update

### ISSUE THREAD

**Issue by tukanos** [nunofarruca/WindowIsReady_Remover#27]
I updated the extension today.  Right after the update I started to get an error:

`gnome-shell[2922]: error: Unable to lock: Lock was blocked by an application`

After disabling the extension the problem went away.  Probably something is missing from the update

**Comment by nunofarruca** [comment]
Can you tell me some info about the distribution you are using so I can try replicate it on a VM?

**Comment by tukanos** [comment]
> 
Of course, my linux version is the following:

Operating System: Debian GNU/Linux bookworm/sid   
          Kernel: Linux 6.0.0-2-amd64
    Architecture: x86-64

I'm using Xorg with Gnome 43.

I hope this helps.

**Comment by nunofarruca** [comment]
I'll have a look, on gnome 43 maybe current code is not 100% compatible but on gnome 42 it should just work. I'll be honest, I just changed the version support to include 43, so its same code as it always was.

**Comment by nunofarruca** [comment]
Well, I installed Fedora 37 beta, installed the extension and tested and journalctl does not show any error and when enabled, the extension work and prevents the popup.
Can you remove the extension and reinstall it fresh to confirm behavior is still the same?

**Comment by joebeaversilverdoor** [comment]
I had uninstalled and reinstalled a couple of times and it didn't work, however this morning it did work. Perhaps there was an issue with Gnome shell integration on chrome

**Comment by tukanos** [comment]
I have tried to remove it and install it again.  To my surprise it worked!

**Comment by joebeaversilverdoor** [comment]
It installs now but i still get the window is ready notifications so no idea what's going on
