### ISSUE TITLE
Error updating/installing

### ISSUE THREAD

**Issue by joebeaversilverdoor** [nunofarruca/WindowIsReady_Remover#29]
Since this morning's update I now receive an error having updated and I cannot now install either
![image](https://user-images.githubusercontent.com/102979545/233624500-e7544bdf-76b9-48c6-b6c6-64b9c254ec18.png)

Ubuntu 22.04.2 LTS
GNOME Version 42.5

**Comment by nunofarruca** [comment]
Thanks for reporting it, I disabled the latest version 
It only added the gnome 44 to be allowed to install, no other change happen on the code.
I will try to find out some time and test it properly, installing that version in a VM and see what happens on update

**Comment by upward4** [comment]
I've tried the extension with GNOME 44, and it doesn't seem to work any more.

**Comment by Donokami** [comment]
Same here, isn't available for GNOME 44.

**Comment by nunofarruca** [comment]
I'll have a look at this very soon, life just got in the way... sorry

**Comment by nunofarruca** [comment]
Just tested today, and there was a bug preventing the extension from installing on gnome 44. 
if you are on the latest version of gnome 44 it will work fine. tested on fedora 38
