### ISSUE TITLE
Update needed on extensions.gnome.org

### ISSUE THREAD

**Issue by k1gen** [nunofarruca/WindowIsReady_Remover#31]
If I install the extension from https://extensions.gnome.org/extension/1007/window-is-ready-notification-remover/, Gnome Extension Manager tells me that the extension is outdated. If I copy the files by hand from git master, it says that update is available and when I relogin I'm being reverted to an outdated version from extensions.gnome.org.

**Comment by nunofarruca** [comment]
I'll have a look at this very soon, life just got in the way... sorry

**Comment by k1gen** [comment]
take all the time you need, no need to say sorry :)

**Comment by nunofarruca** [comment]
tested today on fedora 38 and 39, gnome 44 and 45 and both are working fine
