### ISSUE TITLE
Add link to extensions.gnome.org

### ISSUE THREAD

**Issue by Flimm** [nunofarruca/WindowIsReady_Remover#34]
I came across this extension on GitHub. It would be useful if a link to the extension on extensions.gnome.org was included in README.md, so that I can easily go to that page and install the extension.

Here's the link:

https://extensions.gnome.org/extension/1007/window-is-ready-notification-remover/

**Comment by nunofarruca** [comment]
you are absolutely right! 

thanks for the idea, added!

Cheers

**Comment by Flimm** [comment]
Thank you!
