### ISSUE TITLE
Title not sorted correctly in lists

### ISSUE THREAD

**Issue by lonix1** [nunofarruca/WindowIsReady_Remover#5]
Because the title is `'Windows is Ready' Notification Remover` then it is always at the top of lists, and is not sorted by `W`, because of the `''`.

I know this is a silly request :smile:, just putting it here for consideration. Feel free to close this if you disagree, and thanks for this helpful extension!

**Comment by nunofarruca** [comment]
Well I updated the title to remove the '' from there :) Nice call, thanks.
Did the same on the Gnome extensions entry.

**Comment by lonix1** [comment]
awesome!
