### ISSUE TITLE
Question: remove specific notifications

### ISSUE THREAD

**Issue by lonix1** [nunofarruca/WindowIsReady_Remover#6]
Extension works perfectly - thanks.

However, when I connect an external USB drive, it will not say for example `MyFiles is now ready`, it will say `MyFiles`. (that's the name of the partition). So of course this extension can't block that notification because it doesn't know about it.

Is there some file I can edit to blacklist such names? I think the extension looks for `FOO is now ready`, so it cannot know about `"MyFiles"`. But maybe I can do this manually?

**Comment by nunofarruca** [comment]
The purpose of the extension is to disconnect the code that handles the Windows Attention Handler event.
It doesn't look for anything text related. You can see that in the extension.js file.

I'm not using a gnome linux version now, so I can't test that scenario.

**Comment by lonix1** [comment]
Thanks, I'll try edit that js.
